language: node_js
node_js:
  - 17

services:
  - docker

# Pre testing installs
install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker-compose -f docker-compose.yml build --parallel
  - docker tag post-service "${DOCKER_USERNAME}/post-service:v2"
  - docker tag login-service "${DOCKER_USERNAME}/login-service:v1"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "${DOCKER_USERNAME}/post-service:v2"
  - docker push "${DOCKER_USERNAME}/login-service:v1"