version: "3"
services:
  post-service:
    build:
      context: ./server/post-service
    image: post-service
  login-service:
    build:
      context: ./server/login-service
    image: login-service
  