version: "3"
services:
  reverseproxy:
    build:
      context: ./server/reverseproxy
    image: reverseproxy
  post-service:
    build:
      context: ./server/post-service
    image: post-service
  login-service:
    build:
      context: ./server/login-service
    image: login-service
  frontend:
    build: 
      context: ./client
    image: frontend
