version: "3"
services:
  reverseproxy:
    build:
      context: ./server/reverseproxy
    image: reverseproxy
  post-service:
    build:
      context: ./server/post-service
    image: post-service
  login-service:
    build:
      context: ./server/login-service
    image: login-service
  frontend:
    build: 
      context: ./frontend
    image: frontend
    command: npm start
    ports: 
      - 5000:5000
    working_dir: /app
    volumes:
      - './:/app'
      - '/app/node_modules'