AWSTemplateFormatVersion: 2010-09-09
Metadata:
  License: Apache 2.0
Description: 'CloudFormation template for Student Plaza project stack'
Resources:
  PostDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: PostDynamoDBTable
      AttributeDefinitions:
        - AttributeName: postId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: postId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

                    
