apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-post
  name: backend-post
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: backend-post