apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-post
  name: backend-post
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-post
  template:
    metadata:
      labels:
        service: backend-post
    spec:
      containers:
      - image: rinklerani/post-service:v2
        name: backend-post
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: TABLE_NAME
        restartPolicy: Always
