apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-login
  name: backend-login
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    service: backend-login