apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-login
  name: backend-login
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-login
  template:
    metadata:
      labels:
        service: backend-login
    spec:
      containers:
      - image: rinklerani/login-service:v1
        name: backend-login
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: RDS_HOSTURL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: RDS_USERNAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: RDS_PASSWORD
      restartPolicy: Always
