apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-post
  name: backend-post
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-post
  template:
    metadata:
      labels:
        service: backend-post
    spec:
      containers:
      - image: rinklerani/post-service:v2
        name: backend-post
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        env:
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE
        - name: TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: TABLE_NAME
        - name: RDS_HOSTURL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: RDS_HOSTURL
        - name: RDS_PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: RDS_PORT
        - name: RDS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: RDS_DATABASE_NAME
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: RDS_USERNAME
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: RDS_PASSWORD
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: ACCESS_KEY_ID
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: SECRET_ACCESS_KEY
      restartPolicy: Always