apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: student-plaza-service
  name: student-plaza
spec:
  replicas: 1
  selector:
    matchLabels:
      service: student-plaza-service
  template:
    metadata:
      labels:
        service: student-plaza-service
    spec:
      containers:
      - image: rinklerani/post-service:v2
        name: post-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: TABLE_NAME
        restartPolicy: Always
