apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - image: frontend
        name: frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: TABLE_NAME
        restartPolicy: Always