apiVersion: v1
kind: Service
metadata:
  labels:
    service: student-plaza-service
  name: student-plaza-service
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: student-plaza-service